name: Mi primer Push

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  info-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Datos del Pull Request
        run: |
          echo "Título:          ${{ github.event.pull_request.title }}"
          echo "Contenido:       ${{ github.event.pull_request.body }}"
          echo "Estado:          ${{ github.event.pull_request.state }}"
